### ISSUE TITLE
Deploy to Azure - Error

### ISSUE THREAD

**Issue by sfour** [OfficeDev/microsoft-teams-stickers-app#21]
When I tried to deploy the app in Azure, keep receiving following error,

<img width="802" alt="Screen Shot 2019-06-14 at 9 52 13 AM" src="https://user-images.githubusercontent.com/2275098/59525075-3e197e80-8e8a-11e9-89fd-4982f281fe13.png">

and more details
<img width="519" alt="Screen Shot 2019-06-14 at 9 55 21 AM" src="https://user-images.githubusercontent.com/2275098/59525184-89cc2800-8e8a-11e9-9fff-bbd703bd9a91.png">

Thanks in Advance,

Joe
,

**Comment by MattSFT** [comment]
Looks like Azure failed to register the MSTeams channel for your bot registration. Take a look in azure at your bot channel registration (should be called ZenlayerStickers) and make sure that the channel for MSTeams has been enabled:
![image](https://user-images.githubusercontent.com/29067893/59530399-56909580-8e98-11e9-9e9e-c6dd01789a01.png)

**Comment by MattSFT** [comment]
@sfour were you able to get this working?

**Comment by aosolis** [comment]
@sfour There was a regression in the Azure provider for Azure Bot Services, which is why you got that error.  The owning team has since fixed that on June 19, so future deployments should be working now. We do apologize for the inconvenience!

As MattSFT mentioned above, the easiest fix in your case would be enable the Teams channel.
